### ISSUE TITLE
Install instructions on ng1 getting started are outdated

### ISSUE THREAD

**Issue by jrabbe** [ui-router/ui-router.github.io#26]
The instructions to install ui-router on https://ui-router.github.io/ng1/ refers to the npm package `angular-ui-router`, but should reflect the renaming to `@uirouter/angularjs` noted in https://github.com/angular-ui/ui-router/blob/master/CHANGELOG.md#100-2017-04-30

**Comment by pamo** [comment]
Seems to have been fixed by 90585e9230ef9519450f7dc51c9d8264bc4856b1 @jrabbe

**Comment by jrabbe** [comment]
Thank you @pamo. Closing since this is fixed.
