### ISSUE TITLE
References for services of @uirouter/angular 7.0.0 not found

### ISSUE THREAD

**Issue by rch850** [ui-router/ui-router.github.io#40]
How to reproduce:

1. Open https://ui-router.github.io/ng2/docs/latest/ or https://ui-router.github.io/ng2/docs/7.0.0/
1. Click "[StateService](https://ui-router.github.io/ng2/docs/latest/classes/_uirouter_core_state_stateservice.stateservice.html)" on the right column.
1. Page Not Found

It is strange because the [html file](https://github.com/ui-router/ui-router.github.io/blob/master/_ng2_docs/latest/classes/_uirouter_core_state_stateservice.stateservice.html) exists.

**Comment by cloakedninjas** [comment]
Bump ?

**Comment by christopherthielen** [comment]
Fixed, sorry about that.
