### ISSUE TITLE
Mention $viewContentLoading event removed in 1.0

### ISSUE THREAD

**Issue by hackel** [ui-router/ui-router.github.io#9]
Just discovered this while upgrading.  It should probably be added to the breaking changes section of the migration guide, unless it's going to be added back.

**Comment by christopherthielen** [comment]
weird, where did it go???

**Comment by christopherthielen** [comment]
[Some clown just nuked it with no explanation](https://github.com/angular-ui/ui-router/commit/19544954cf67a138739df1f21bbc278741a8e913#commitcomment-20267563)
